DROP DATABASE LMS;
CREATE DATABASE LMS;
CONNECT LMS;

CREATE TABLE USERH(
  USERID INT PRIMARY KEY     NOT NULL,
  NAME           TEXT    NOT NULL
);

CREATE TABLE LEAVE(

  USERID INT    NOT NULL  REFERENCES USERH(USERID) ,
  LEAVEDATE           DATE  NOT NULL,
  LEAVETYPE           VARCHAR   NOT NULL,
  REASON VARCHAR (50),
  COMMENT VARCHAR (100),
  PRIMARY KEY(USERID,LEAVEDATE)

);

CREATE TABLE LOGINUSER(
  USERNAME VARCHAR  PRIMARY KEY NOT NULL,
  EMAIL  VARCHAR   NOT NULL
);


INSERT INTO USERH VALUES ('001','cook');
INSERT INTO USERH VALUES ('002','hameed');
INSERT INTO USERH VALUES ('003','root');
INSERT INTO USERH VALUES ('004','duncket');
INSERT INTO USERH VALUES ('005','ali');
INSERT INTO USERH VALUES ('006','stroke');
INSERT INTO USERH VALUES ('007','bestrow');


INSERT INTO LEAVE VALUES ('001','2016-10-01','full day','sick','');
INSERT INTO LEAVE VALUES ('001','2016-10-02','full day','sick','');
INSERT INTO LEAVE VALUES ('001','2016-10-10','full day','sick','');
INSERT INTO LEAVE VALUES ('002','2016-10-01','first half','sick','');
INSERT INTO LEAVE VALUES ('002','2016-10-21','second half','sick','');
INSERT INTO LEAVE VALUES ('002','2016-10-25','second half','sick','');


INSERT INTO LOGINUSER VALUES ('nuwantha','nuwantha.13@cse.mrt.ac.lk');
INSERT INTO LOGINUSER VALUES ('akila','akilac.13@cse.mrt.ac.lk');
