DROP DATABASE LMS;
CREATE DATABASE LMS;
CONNECT LMS;

CREATE TABLE USERH(
  USERID INT PRIMARY KEY     NOT NULL,
  NAME           TEXT    NOT NULL
);

CREATE TABLE LEAVE(

  USERID INT    NOT NULL  REFERENCES USERH(USERID) ,
  LEAVEDATE           DATE  NOT NULL,
  LEAVETYPE           VARCHAR   NOT NULL,
  PRIMARY KEY(USERID,LEAVEDATE)

);

INSERT INTO USERH VALUES ('001','cook');
INSERT INTO USERH VALUES ('002','hameed');
INSERT INTO USERH VALUES ('003','root');
INSERT INTO USERH VALUES ('004','duncket');
INSERT INTO USERH VALUES ('005','ali');
INSERT INTO USERH VALUES ('006','stroke');
INSERT INTO USERH VALUES ('007','bestrow');


INSERT INTO LEAVE VALUES ('001','2016-10-01'.'full');
INSERT INTO LEAVE VALUES ('001','2016-10-02','full');
INSERT INTO LEAVE VALUES ('001','2016-10-10','full');
INSERT INTO LEAVE VALUES ('002','2016-10-01','half');
INSERT INTO LEAVE VALUES ('002','2016-10-21','full');
INSERT INTO LEAVE VALUES ('002','2016-10-25','full');
